'use client';
import React from 'react';
import { ImageOff } from 'lucide-react';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
// import { useRouter } from 'next/navigation';

const NotFound = () => {
  // const router = useRouter();

  return (
    <motion.div
      className="relative flex flex-col min-h-[90vh] items-center justify-center gap-10 px-4 text-center  "
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
    >
    
      {/* Icon */}
      <div className="flex items-center justify-center w-24 h-24 rounded-full bg-red-100 dark:bg-red-900/20 shadow-md">
        <ImageOff className="w-12 h-12 text-red-500 dark:text-red-400" />
      </div>

      {/* Heading */}
      <div>
        <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-white mb-3">
          Nothing to see here
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-400 max-w-xl mx-auto">
          But hey! Here's a random image generated by
          <span className="text-purple-500 font-medium"> Creative AI</span>.
        </p>
      </div>

      {/* Optional: Show random image */}
     <motion.img
  src="/iron man.png"
  alt="Creative AI Output"
  className="w-[200px] h-[200px] object-cover rounded-xl shadow-lg  dark:border-gray-800"
  whileHover={{ scale: 1.05 }}
  transition={{ duration: 0.3 }}
/>


      {/* Button to go home */}
      <Link href="/">
        <Button variant="default" className="text-base px-6 py-2 mt-4">
          Go Home
        </Button>
      </Link>
    </motion.div>
  );
};

export default NotFound;
